### ISSUE TITLE
Functions "*.disconnect()" and "*.end()" doesn't work

### ISSUE THREAD

**Issue by mwms** [01org/corelibs-arduino101#97] opened 2016-01-05 16:45 UTC
example
ble_peripheral.end()
central.disconnect()

**Comment by kitsunami** [comment] 2016-02-24 22:37
To Sidney, to be worked on with JIRA 544.

**Comment by SidLeung** [comment] 2016-05-27 00:04
Please note that the current Arduino platform can only be a Peripheral, no Central features are available.  If you are trying to finding out if your board is still connected to the host, you can use the method, BLECentral::connected().

**Comment by sandeepmistry** [comment] 2016-05-27 13:24
@SidLeung I looked into this a few months ago, the issue is ```central.disconnect()``` does not trigger a disconnection of the connected central. From what I remember the handle book keeping in `CurieBLE` looked ok, I suspect there is something wrong on the nRF51 f/w side or incorrect messaging format.

**Comment by SidLeung** [comment] 2016-05-27 15:30
@sandeepmistry Thanks for the info.  Will track that down,

**Comment by ccoulton** [comment] 2016-08-16 23:01
Related Question, is there a way to start advertising with an interrupt? end seems to work when not connected to a central, but restarting the perhipheral seems impossiable.

**Comment by eriknyquist** [comment] 2016-09-29 02:26
@SidLeung any idea if this has been fixed in the recent BLE merge?

**Comment by noelpaz** [comment] 2016-10-11 01:40
I verified that disconnect and end works from a peripheral using the API disconnect and end for the current CurieBLE implemented by @sgbihu  (Liang's team) . I am closing this.


Thanks

**Closed by noelpaz** 2016-10-11 01:40 UTC
Labels: bug, Pending Implementation
